name = "blog-music-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "BLOG"
id = "445938d2930b4098a1d7e52500761ee2"

[[r2_buckets]]
binding = "R2"
bucket_name = "blog-music-files"
